### ISSUE TITLE
yolo.tflite的模型是如何训练的

### ISSUE THREAD

**Issue by w910820618** [mushroom-x/K210_Tutorial#2]
我想请教一下，example里面的tflite文件是怎么训练得到的，方便的话，可以提供一下代码吗？我想要自己训练一个yolov3的模型。

**Comment by mushroom-x** [comment]
我用到的tflite模型是通过tf自带的工具转换的.
文档里有说明

**Comment by LiJunJie27** [comment]
> 我用到的tflite模型是通过tf自带的工具转换的。
> 文档里有说明

我用Maix_Tool中的pb2tflite.sh转换pb模型时出现如下问题：
 W tensorflow/contrib/lite/toco/toco_cmdline_flags.cc:178] --input_type is deprecated. It was an ambiguous flag that set both --input_data_types and --inference_input_type. If you are trying to complement the input file with information about the type of input arrays, use --input_data_type. If you are trying to control the quantization/dequantization of real-numbers input arrays in the output file, use --inference_input_type.
 F tensorflow/contrib/lite/toco/toco.cc:46] Check failed: parsed_toco_flags.input_file.specified() Missing required flag: input_file
不知作者是否遇到过，能否给出python以及tensorflow的版本
